package com.example.Areanixx.Entity;

import java.time.Instant;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.validation.constraints.NotNull;

@Entity
public class Achievement {

	public Long getId() { return id; }
	public void setId(Long id) { this.id = id; }
	public Long getPlayerId() { return playerId; }
	public void setPlayerId(Long playerId) { this.playerId = playerId; }
	public PlayerProfile getPlayer() { return player; }
	public void setPlayer(PlayerProfile player) { this.player = player; }
	public Long getTournamentId() { return tournamentId; }
	public void setTournamentId(Long tournamentId) { this.tournamentId = tournamentId; }
	public Tournament getTournament() { return tournament; }
	public void setTournament(Tournament tournament) { this.tournament = tournament; }
	public String getTitle() { return title; }
	public void setTitle(String title) { this.title = title; }
	public Boolean getAutoGenerated() { return autoGenerated; }
	public void setAutoGenerated(Boolean autoGenerated) { this.autoGenerated = autoGenerated; }
	public Instant getCreatedAt() { return createdAt; }
	public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@NotNull(message = "Player id is required....")
	@Column(name = "player_id")
	private Long playerId;

	@ManyToOne
	@JoinColumn(name = "player_id", insertable = false, updatable = false)
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private PlayerProfile player;

	// nullable - only set when achievement came from a tournament
	@Column(name = "tournament_id")
	private Long tournamentId;

	@ManyToOne
	@JoinColumn(name = "tournament_id", insertable = false, updatable = false)
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Tournament tournament;

	@NotNull(message = "Title is required....")
	private String title;

	private Boolean autoGenerated = true;

	private Instant createdAt;

	@PrePersist
	protected void onCreate() {
		this.createdAt = Instant.now();
	}

}
